### ISSUE TITLE
BlaaHund response in text/plain instead text/html

### ISSUE THREAD

**Issue by ulslevpedersen** [t-crest/iot-rt#1]
Should we change from text/html to text/plain when the http server gives the informational response to any http request?
It will make it nicer to look at in the commandline based programs that run the tests. When used from the browser it looks nice even in plain text.

**Comment by schoeberl** [comment]
Both is fine for me.

**Comment by ulslevpedersen** [comment]
Ok, let's try text/plain then.

**Comment by schoeberl** [comment]
Ok, changed it.
